# Generated by Django 3.2.7 on 2021-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ball',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tennistable',
            options={},
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='url',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='slug',
            field=models.SlugField(default=1, unique=True, verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='subimage',
            name='sub_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Дополнительное изображение'),
        ),
    ]
