# Generated by Django 3.2.7 on 2021-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ship_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
