# Generated by Django 3.2.7 on 2021-10-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211021_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('discontinued', 'нет в наличии'), ('popular', 'популярный'), ('best_seller', 'хит продаж')], default='popular', max_length=255, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
