# Generated by Django 3.2.7 on 2021-10-23 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_product_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
