# Generated by Django 3.2.7 on 2021-10-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211023_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='position',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
