# Generated by Django 3.2.7 on 2021-10-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211002_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subimage',
            name='img',
        ),
        migrations.AddField(
            model_name='subimage',
            name='sub_image',
            field=models.URLField(blank=True, null=True, verbose_name='Дополнительное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Основное изображение'),
        ),
    ]
