# Generated by Django 3.2.7 on 2021-10-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211002_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subimage',
            options={'verbose_name_plural': 'Sub Images'},
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_product_data', to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Balls',
            },
        ),
    ]
