# Generated by Django 3.2.7 on 2021-10-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_description_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sliderinfo',
            name='text',
        ),
        migrations.AddField(
            model_name='sliderinfo',
            name='base',
            field=models.TextField(default='basetext', verbose_name='Содержание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderinfo',
            name='header',
            field=models.TextField(default='header', verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='SliderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.TextField(verbose_name='Подзаголовок')),
                ('base', models.TextField(verbose_name='Содержание')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='mainapp.sliderinfo', verbose_name='Слайдер')),
            ],
        ),
    ]
