# Generated by Django 3.2.7 on 2021-10-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211008_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='url',
            field=models.URLField(default='https://github.com/FairaIchsa/market_django_v1', unique=True),
        ),
    ]
