# Generated by Django 3.2.7 on 2021-10-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211023_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderinfo',
            old_name='image',
            new_name='img',
        ),
    ]
