# Generated by Django 3.2.7 on 2021-10-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_image_sliderinfo_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sliderinfo',
            old_name='header',
            new_name='main',
        ),
    ]
