# Generated by Django 3.2.7 on 2021-10-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_rename_header_sliderinfo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderinfo',
            name='text_1_base',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание 1'),
        ),
        migrations.AddField(
            model_name='sliderinfo',
            name='text_1_main',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок 1'),
        ),
        migrations.AddField(
            model_name='sliderinfo',
            name='text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='sliderinfo',
            name='text_3_base',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание 3'),
        ),
        migrations.AddField(
            model_name='sliderinfo',
            name='text_3_main',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок 3'),
        ),
        migrations.AddField(
            model_name='sliderinfo',
            name='text_4',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 4'),
        ),
        migrations.DeleteModel(
            name='SliderText',
        ),
    ]
