# Generated by Django 3.2.7 on 2021-10-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_menucategory_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.URLField(verbose_name='Изображение')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Slider info',
            },
        ),
    ]
