# Generated by Django 3.2.7 on 2021-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20211026_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderinfo',
            name='base',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='main',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_1_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_1_main',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_3_base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_3_main',
            field=models.TextField(blank=True, null=True),
        ),
    ]
