# Generated by Django 3.2.7 on 2021-10-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_sliderinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldable', models.BooleanField(default=False, verbose_name='Складной')),
                ('folded_size', models.CharField(max_length=255, verbose_name='Размер в сложенном состоянии')),
                ('unfolded_size', models.CharField(max_length=255, verbose_name='Размер в разложенном состоянии')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_product_tennis_table', to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Tennis tables',
            },
        ),
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='Размер')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_product_ball', to='mainapp.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name_plural': 'Balls',
            },
        ),
    ]
