# Generated by Django 3.2.7 on 2021-10-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20211026_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderinfo',
            name='base',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='main',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_1_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_1_main',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст 2'),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_3_base',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_3_main',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sliderinfo',
            name='text_4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст 4'),
        ),
    ]
