# Generated by Django 3.2.7 on 2021-10-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennistable',
            name='folded_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер в сложенном состоянии'),
        ),
    ]
