# Generated by Django 3.2.7 on 2021-10-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20211027_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ship_address',
            new_name='ship_adress',
        ),
    ]
