# Generated by Django 3.2.7 on 2021-10-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_rename_ship_address_user_ship_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ship_adress',
            new_name='ship_address',
        ),
    ]
