# Generated by Django 3.2.7 on 2021-11-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_rename_ship_adress_user_ship_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
